name: Run Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest --junitxml=report.xml

    - name: Commit test results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        python tests/update_readme.py
        git add README.md
        git commit -m "Update test results in README"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}